export const LOGIN_CHANGE = 'LOGIN_CHANGE';
export const LOGIN_RESET = 'LOGIN_RESET';
export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING';
export const SET_LOGIN_FORM_ERRORS = 'SET_LOGIN_FORM_ERRORS';
export const SET_LOGIN_SUBMITTING = 'SET_LOGIN_SUBMITTING';
